---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/storage/garage-ui/ks.yaml

patches:
  - target:
      kind: Kustomization
      name: garage-ui
    patch: |-
      - op: replace
        path: /spec/path
        value: ./kubernetes/apps/production/storage/garage-ui/app
