apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin-password
spec:
  refreshInterval: 10s
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: grafana-admin-password
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: GF_SECURITY_ADMIN_PASSWORD
      remoteRef:
        key: secrets/observability/grafana-operator/admin-password
        property: GF_SECURITY_ADMIN_PASSWORD
