---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/security/vaultwarden/ks.yaml

patches:
  - target:
      kind: Kustomization
      name: vaultwarden
    patch: |-
      - op: replace
        path: /spec/path
        value: ./kubernetes/apps/production/security/vaultwarden/app
  - target:
      kind: Kustomization
      name: vaultwarden-database
    patch: |-
      - op: replace
        path: /spec/path
        value: ./kubernetes/apps/production/security/vaultwarden/database
