---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPClusterConfig
metadata:
  name: bgp-cluster-config
spec:
  bgpInstances:
    - name: instance-12345
      localASN: 64514
      peers:
        - name: peer-64513-v4
          peerASN: 64513
          peerAddress: 192.168.20.1
          peerConfigRef:
            name: bgp-peer-config-v4
