image: renovate/renovate:35.62

stages:
  - renovate

variables:
  RENOVATE_BASE_DIR: $CI_PROJECT_DIR/renovate
  RENOVATE_GIT_AUTHOR: Renovate Bot
  RENOVATE_OPTIMIZE_FOR_DISABLED: "true"
  RENOVATE_REPOSITORY_CACHE: "true"
  LOG_LEVEL: debug

cache:
  key: ${CI_COMMIT_REF_SLUG}-renovate
  paths:
    - $CI_PROJECT_DIR/renovate

run_renovate:
  stage: renovate
  resource_group: production
  only:
    - schedules
  script:
    - renovate $RENOVATE_EXTRA_FLAGS
