---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/external-services/openbao-internal/external

patches:
  - target:
      kind: HTTPRoute
      name: openbao-internal
    path: ./httproute.yaml
