apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vaultwarden-secrets
spec:
  refreshInterval: 10s
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: vaultwarden-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: ADMIN_TOKEN
      remoteRef:
        key: secrets/security/vaultwarden/config-secrets
        property: ADMIN_TOKEN
    - secretKey: SSO_CLIENT_ID
      remoteRef:
        key: secrets/security/vaultwarden/config-secrets
        property: SSO_CLIENT_ID
    - secretKey: SSO_CLIENT_SECRET
      remoteRef:
        key: secrets/security/vaultwarden/config-secrets
        property: SSO_CLIENT_SECRET
    - secretKey: PUSH_INSTALLATION_ID
      remoteRef:
        key: secrets/security/vaultwarden/config-secrets
        property: PUSH_INSTALLATION_ID
    - secretKey: PUSH_INSTALLATION_KEY
      remoteRef:
        key: secrets/security/vaultwarden/config-secrets
        property: PUSH_INSTALLATION_KEY
