apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-secrets
stringData:
  ADMIN_TOKEN: ENC[AES256_GCM,data:0xYf4/OzBQ+f6hc35hBsMPRYxTBlea4fPle4NrHgM7Y5L9HFT8KH4SCqaz78TA/KeLKO/bfa9F3pvNcPFhpZxQ==,iv:eJ1hub6WIInqlNrX+a8aOdX9X8dEVBYAJfqSsMUBpvk=,tag:nsVbVfT612NcQywOu5mWgA==,type:str]
  SSO_CLIENT_ID: ENC[AES256_GCM,data:h5VibaAdTM3TsZei43MJH20Zzhku7hiHVhhNk8aYw/v0/vsh0kzP3w==,iv:ZSCmoctYi4gk9VpMW8aHQIQH7bS4FdVfZIWMIbqsEjc=,tag:JebjNC/pOw6d2Cbk/+Nqww==,type:str]
  SSO_CLIENT_SECRET: ENC[AES256_GCM,data:9udF38J+oWDnyXstwQ1cXtnBliKhCXPzpuooKC2Vou6XMexY0euM7d2t49EzQqGi1b5VFFCnOs+fYPDW+Uv5iHXz1aTglpzvR+lTlzmdx6ij75PfsUvhoQbaJYxebMQ67gWcCGpgskP5uxDucVNk7CfiUGeWi9IgpnjwAhgYw7k=,iv:o/85/bMsXCEMxdDKAKKPnhMbvLkG/kuVKsqzu1/ELZw=,tag:b4Hoh6+D/sLTcDVzeRrL6g==,type:str]
  PUSH_INSTALLATION_ID: ENC[AES256_GCM,data:VrQGJvMQcYEArKVA4PFmTr5TMqmvZASlxxq8i8VZqH44Py2V,iv:sEO0GyCmjhk56GzIiyUoNxvrI080VswUkNMc8lyCDu4=,tag:oqTcfPUzjn5bsK+0NbEZAg==,type:str]
  PUSH_INSTALLATION_KEY: ENC[AES256_GCM,data:mancMJcedN7OHCy9smypR4Ip9SI=,iv:O52HFeo8/aU8hHWC4Pb3HuxX4M+C/k6kiJvJ1KnAsYM=,tag:H6zKDJVX8PSeZLPL+j6tsg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFMwVGkwRDlJ
        a2o0Tm5oc1NoRE1XbVgyRWF3c3VqVGF5MVF1SWJ1SHFtZlVxWlZJZmlUdkhBT1NT
        dTZnSFZCNy9qRG14dHRCWmN3RGVwbGl4U3ZkWGJwamF0eU1xZXJLZ1J5T2J4bW1i
        MVNMWmRyTG9IUVdoRkVvV1pyb0xwSFRSMUhEQzhUeVZVeEtjU1FNb0dEODN6SDBj
        T3lhZ1VEWk83MVFwVjJxU3g1elk0R3JyL0FQV0hBbzdKQ3NrVmNHUFFYd3V4Y0NV
        UkVObk5YaU9LYUQ4cXNPYWxFVUhTRFo2Q2tkSU1YdXVMMXJBc3pkbzFRaTQzTE45
        aGZBdG1ZZVJmcU0rbllDWGlIeUxZNzROVHRQcTJtTVhJWE5uV2xBOHNZdVBROWt3
        bXhVVWNFdGw5TVM3UHpwYUcrUmp3VXl4K09VYTc5aklIZXhjaWtsb2FrYkdRR0ZY
        Mk9vRUQvNjE4TmNtNk5DNkQ4ZUNJVkdZeGZWV0kycUVJcE43WDBWeHNqYzdHMGtt
        TU11elVjR3dRRlU0Q1Z0djhBekRhT1FJeGFFZllUUHV1SUV5MWZUM0VSeUVjL0xT
        ZXpjMmhZMlNEamQ4Z3BhaU5nMkFhczZTR052SlFtYjJqbURpSWFyaTN5RzhiRWJF
        elVxUVYxUSs2OHQrNmJaUnJuN052anpoSkIrWHJkY1UwY1FhVVl1NElmZVZVd1ox
        NHJYQnZNMWF0Vk1sblFISWgvVDZSaXRTSTZuZDdCalRDbVVXTFR6anZKa3VpQzd5
        M0JGU201S0p2QzhSRmcyM3N4cWtlT3BhSHMrQnlYcitjK3pFYlYvaHJIUGZtbGFZ
        elhpQnNhSG5JQ0luZ0VaWHZPWkRiTWJqdFdCQjJYWkRZK2tMVVd5Z2FjUklWQVBl
        Z05SWG1yZURUUnlPb2Y3R2VpWnJmSFRmL2ZjamNvRjJhcUhReFpsb0w3Ukk1MXVL
        OS9PVDVqTzJGbFk3dWV4a2NjR1hDamdLQU1TNVlmbWY5aGpXWDZXTnVNZ0pHWDdF
        eXBuTlp2MG1tNmx5N0V2VW9pWDk4OFJkODcxQnJUa291dlh5c1FwUjM0ZUM2WUtO
        R2ZOa2djeGo4QVVCK1Fic21tZWlrd2R0QzVTQ0thazRsZkxlMmFsU2ZqeG5qWVZr
        Vmc2TVQ1YllIeTNPWkRwdkoyK0V5bFcwYWlkNzZFRTVCLzIrZWF5RDVJMWw1ckZQ
        QUZyK2FkbGpIdjNSSkdURVlqbnp2NFR2Q1FwSU43VmZLa0R3WTlaZXpodkNXaTlq
        MmZIcXd4WXNIU1RGT29SRlV2eUE1V1hWMFJBTXBROXhHNnQzdGtrU2lBdTNIY1Jw
        TlRRY3ZBR2trakE1SVl5dEMwMVB3V0crcVhCa3lPdDRKWXJkdGhYT0xVSndyMHQ3
        a0hha0RiUVMzM0taZ3VhNjJnTjE0WmtEcUdsM1ppcTdpN1Q4dytqRVVFVDNqUnVN
        b0VDQUNPUzkzb3Yzanh3bGs5MXdmcDhNbWxTM2daTmpTQ2dON1dzM0UzcU1PVGV6
        dTgwQlNxeFRoUmFUaEdpcnFQR2pWU0MzRWVMRGROY3p4TFJ6NnFMNmFtTzVrZGcw
        SjBJZnZJazBQaVRpR1dNdGRaTERkSFdZUVFJVmhzMHBqNzVhblB2ekhIT3p1UFVv
        Tnc5N3pLbWdGU2grWENVMGdGeWJpZlJFWjRLc3lkU3g5TXk0L2NtU0dLd00vR3BQ
        aUdtMDl2WHFEY0Q3RGJXS3M5YklJRkplY1FrSStteUszMmNDWlJicEQveDNNWkwy
        TmV3TlVmYVc1dVlPdVJSOWR5K1NaUzZJWERPQkVrRmUrS3ZZOEVia2FvRVVYSkZy
        cGJiRkFVbGgyNllRQXZNQ2sxbE1ieHovOUNXclhHYmRyR1Q2VjZnTmNtSjllbkJx
        WDMwTnIvQjc4UGk5OVp5N3REREowZG1iN3lXYThEVXRGcjcxMDFVUnNhekFjdwpI
        Y2oyS1ltSmo2SmVTc3pSTVJhODRzeUNaVngvL1lZQWxGdm8zYTlaRWtvCi0tLSAy
        L0g0eGJ3S01weU1sb3FyWlB5WWVmcGY5eDl3WTNDZkNCd3ZrYURXTUF3Cr1WcQ22
        jPxq7NQ/PD8OVSGOUak+6hJXNLvOpqnZ0xj2nbD+BBlMwcHbkPvOYHyMzIlKhKp5
        S6XJA4MP+aI3+yo=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1a523qrltc5tc2c97s7eku9stpt386g86jqd50zt2zdlpv7nn76yyfg69ra80ct06746j03chk3e83snj3gn0ctkgxwp96vat87j2z4js5yamnnf96eqgn6zlfqngg95jz24f58hysvud6qrdqtc3uqh6scmpdg4ergtu3pd8zkpnsczfs6sq80nu5ch5g6uf6l95532qec80c86pw95tqsnmvcmmlph8xwvzwuea0x3r90qq05jesjkg0nt98qr42dpfaxzr67zmuchctncy095ccvv3ruc93fnrzn4fsxjtc67ryvzr27tu7vfcnwts3ul6jal5s99gas2eewzcmglq3tz2xre62z53mcpksranxt9qj46xsy9zlzn5lkrucj9rtdmnpa9aess9k58l84v7vgrnvmuew220zmlhdpr04uzpssdxj2hr5nk2vxx8u3mj6cdzhkju4s79rm3jsznpczhyae3qxqg3xwlyysq5v58668qwtargda66fjrexttzx7vhvzjvdv393zuq9cegqwduhfj7w4c2eksrcrrfqzay5e53drumuh8s0s2ygu9fez2qexl3gpxz5xufcef24z5epcs4z6vuzkfls6ur2zzfw9qmhjr4sph7f964gjy895fr6gjgmhlzef86xkc677273wah2xjut28twrtmgwktrwp080q6yl59zxnjyspssjy4ag6yxkgnnhd4u26ysrsevchvaph43yyr8q4ecqr8fttl2v6szjqjl3r7nzjq4j320qgadr5yg39stfq5yqrc7v5h2trw5rwe38xnyccx7fphtqc6tcqmqjzsjyxxfksascahczg3qs3rrwfk8snd4j20amdyufthz8pe8j29zual8pyqa99fjfh88z02jtua53k6t9e7cf59tshfh3ya3nnr22q55qvnqhq2jjnvg7j6y2tfz5f035kypuyx7xdzhaqrndztr3plu43dw0dqljsjtww940ahvp3enkpfzjnvunrntfh5cv0nwxm5sgpcesp6c5kn5zyled8f5shmh9502u5q76lxv394yckdhg8tkxy0e6wqgj8zzc4kn3czvk5wq2f65au3h8wh0e5ywxuff95tp6e3s7wrwdv2rmpud0scgjzpg2rr7uqyzchygu6kx7ukm9d967e0r6sru9urd83rqc4cfxweryutd752ef73te73tnn4axtejvjk3qa8rjqhpvkld8kqpg8yshxrd0cfwqjq8kee2tqm23hfueuu2eqnre6yrm472wx8eykgffghzl3g0y0fd6xjqw224p2zuea77q46cfe5vxwwsvnc5vr35vkvk6q96vjfdnpdtpfnnvmst6djjxmxgdgr9pfjyl8s4qsl6k4ldm6y60xq0g38jnerajlplzp4pwspw4hq4wg29tl2ccxzcv9xwhspytzzng3rhp8qscysyxww8vrm46x9q4fk3jvjv5zjtgaadfnqlw5uqlqh3d66dzlfp2yp33j23w8h9mn6cenx8v36ndyyvk6yjz663rcj4jn2ykryupj48j54r9se2dumw8v0gun5wunj8ft2qxkm2euaj08mzhp6g9fs33dqjc9hyzvsk4a4czxk74urmht906xe99yxjgukvd6v3vgeg3c4f8cttp745cgf5cgkxy94v8ug8awt38yhntvjg28dvmrmv9xfr4s5v8yakt2df3hw7afa6ewqe4upyd5vjpy6sz2pg9fafuwp2xw6y75q9dvwn9n9r232n39ty8hjq7sjw95tmyyarkuwdla85p5gndvu2he5s7eu52cxhm7tfd5nsrnz5tex2pnkggl93grfcsaa0h9tkpknew52n3ew7rxhp06tlpytcvqcrf7yaaeqsl8r09qm9c5ernmx52rt0mx9j66luasmz9y6dmqduwj9kq7q85exdf7q
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-28T00:18:26Z"
  mac: ENC[AES256_GCM,data:wKIgyKoX6pMNqYYMThIdldaXfw+QTR5L4EzVPlNBI4x+E0qFbNn17JmEUV6Wt8pUDtOb3TYk0+PMHUByr5fF+sYshhfu++2JGVtjV5WWGcBcNDZf7iwTcPfswbHIpU2d/Wnkt24FPpmzl0j4EJLlowBnMN1reGikvlXZ5IAhiok=,iv:prBBNekBx8YQemIsQn/gJu9vAFP7VGhVq5nYpSRmB6A=,tag:iblMlukh4oMKwy5s1RYWiA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
