---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/kube-system/generic-device-plugin/ks.yaml

patches:
  - target:
      kind: Kustomization
      name: generic-device-plugin
    patch: |-
      - op: replace
        path: /spec/path
        value: ./kubernetes/infrastructure/production/kube-system/generic-device-plugin/app
