apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-operator-secrets
spec:
  refreshInterval: 10s
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: renovate-operator-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: GITHUB_COM_TOKEN
      remoteRef:
        key: secrets/productivity/renovate/secrets
        property: GITHUB_COM_TOKEN
    - secretKey: RENOVATE_TOKEN
      remoteRef:
        key: secrets/productivity/renovate/secrets
        property: RENOVATE_TOKEN
