apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: renovate-operator
spec:
  chartRef:
    kind: OCIRepository
    name: renovate-operator
  interval: 1h
  values:
    route:
      hostnames:
        - renovate.sud0.net
    authorization:
      defaults:
        readerGroups:
          - renovate-readers
        adminGroups:
          - renovate-admins
        readerUsers: []
        adminUsers: []
        anonymousRead: false
        anonymousReadLogs: false
    auth:
      oidc:
        enabled: true
        issuerUrl: "https://authentik.sud0.net/application/o/renovate/"
        clientId: "Zzmo3SBnyONlLXYz9vyeU6DLdr32NhoKzZxx2WO7"
        existingSecret: "renovate-operator-secrets"
        secretKey: "client-secret"
        additionalScopes: ["groups"]
        fetchUserInfoGroups: false
        redirectUrl: "https://renovate.sud0.net/auth/callback"
        redirectScheme: "https"
        allowedGroupPattern: "renovate-admins"
