---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/productivity/renovate-operator/app
  - ./externalsecret.yaml
  - ./renovatejob.yaml
  - ./configmap.yaml

patches:
  - target:
      kind: HelmRelease
      name: renovate-operator
    path: helmrelease.yaml
