apiVersion: renovate-operator.mogenius.com/v1alpha1
kind: RenovateJob
metadata:
  name: home-ops
spec:
  schedule: "0 20 * * 6"
  discoveryFilters:
    - "nadd3r/home-ops"
  image: renovate/renovate:44.105.4
  secretRef: "renovate-operator-secrets"
  provider:
    name: github
  parallelism: 1
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"
  renovateConfig:
    configMapRef:
      name: renovate-operator-config
      key: renovatorc.json5
