apiVersion: v1
kind: ConfigMap
metadata:
  name: sillytavern-env
data:
  SILLYTAVERN_LISTEN: "true"
  SILLYTAVERN_LISTENADDRESS_IPV4: "0.0.0.0"
  SILLYTAVERN_PORT: "8000"
  SILLYTAVERN_WHITELIST: '["10.42.0.0/16", "10.43.0.0/16", "127.0.0.1"]'
  SILLYTAVERN_WHITELISTMODE: "true"
  SILLYTAVERN_ENABLEFORWARDEDWHITELIST: "false"

  SILLYTAVERN_SSO_AUTHENTIKAUTH: "true"
  SILLYTAVERN_SSO_TRUSTEDPROXIES: '["127.0.0.1", "10.43.0.0/16", "10.42.0.0/16"]'

  SILLYTAVERN_HOSTWHITELIST_ENABLED: "true"
  SILLYTAVERN_HOSTWHITELIST_HOSTS: '["sillytavern.sud0.net"]'

  SILLYTAVERN_ENABLEUSERACCOUNTS: "true"
  SILLYTAVERN_ENABLEDISCREETLOGIN: "true"

  SILLYTAVERN_PRIVATEADDRESSWHITELIST_ENABLED: "true"
  SILLYTAVERN_PRIVATEADDRESSWHITELIST_ALLOWEDRANGES: '["127.0.0.0/8", "10.42.0.0/16", "10.43.0.0/16", "192.168.20.10"]'
