apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: open-webui-secrets
spec:
  refreshInterval: 10s
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: open-webui-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: OAUTH_CLIENT_ID
      remoteRef:
        key: secrets/ai/open-webui/secrets
        property: OAUTH_CLIENT_ID
    - secretKey: OAUTH_CLIENT_SECRET
      remoteRef:
        key: secrets/ai/open-webui/secrets
        property: OAUTH_CLIENT_SECRET
