---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/ai/open-webui/app
  - ./configmap.yaml
  - ./externalsecret.yaml

patches:
  - target:
      kind: HelmRelease
      name: open-webui
    path: ./helmrelease.yaml
