---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

resources:
  - ./namespace.yaml
  - ./cilium/
  - ./coredns/
  - ./spegel/
  - ./reloader/
  - ./metrics-server/
  - ./generic-device-plugin/
  - ./intel-gpu-resource-driver/
