---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/network/adguard-dns/ks.yaml

patches:
  - target:
      kind: Kustomization
      name: adguard-dns
    patch: |-
      - op: replace
        path: /spec/path
        value: ./kubernetes/infrastructure/production/network/adguard-dns/app
