apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: flux-webhook-token
spec:
  refreshInterval: 10s
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: flux-webhook-token
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: token
      remoteRef:
        key: secrets/flux-system/flux-instance/webhook-token
        property: token
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: git-ssh-key
spec:
  refreshInterval: 10s
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: git-ssh-key
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: identity
      remoteRef:
        key: secrets/flux-system/flux-instance/git-ssh-key
        property: identity
    - secretKey: known_hosts
      remoteRef:
        key: secrets/flux-system/flux-instance/git-ssh-key
        property: known_hosts
