apiVersion: v1
kind: Secret
metadata:
  name: flux-webhook-token
stringData:
  token: ENC[AES256_GCM,data:8uRYL/0PnzInAbKvJVyUme7ybj8s01Mt/PtOjtzjmG0=,iv:/rJz3YgW+KUnKYtv3CMMXOOb3kXt+/jMKPzOL2Mp/6g=,tag:CdMaWZVDhV3YN9zGZum2Lw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFlqS2duWkFh
        eWlsWDFOMU1neFh2Y0ptTXFqM29NdVJYcUpQZTZsb2pReTU2dVlUMXkrTENJN1ZF
        eWloelVGN1ZSRmYxUDE2dVhNeEp6TGhOTHc5anpoWUVvMGh3dWYzK1NjZXVuQk9K
        dVJJTW0yM2hWQ0Q4S2lld3ZPZFFsTzRhY3lwYnNzZnF3T2VwdzdwZnZad25FZ2lG
        cVlNZm9XV1FYNmVTamNFL1A1ZmhyOWloZmYwb3RzaWZjckVKb2g5em1sSXhRbmRK
        WTNSZTdUbDBHaGdDanYvQ3VLcmtJeUluZE5GcHFXUGg1QkQrK01EZGVXdmFIKzJL
        N1JIK0lBV01SdTVacEJ4aUljeHVjdEhXMmdKNzZhaG1pRjBCZktTaVdkU3hzNnJ2
        c05xcE5MWjFLNnJ0T3pwSXgrY2V2MlRGa2luUmEwam9BMmFRbjF4Q0FIUEFtRjYr
        a0tDbUFoZU5RN0o4d2RvOVg1MjIzL3ozUUJ5dU9qV2VIVEsvMXI2T1VQYzVkbXRz
        Vmpqa29nYmlRQWVrTkhFTXVzd094NmZ3amhTYlF4UHdxaFdkckZSWEgxdDcxMm9l
        Mnk0dzF5bjVlOC9SdmUreExMU0hINUNpdkZRZnlyWjFOZlF1RjBCWXBpUHZmMDF6
        YWtGR3g4eDFzTUpEaHVnTFhzWWtMVmtUVHJvQUcxeG11anB1ZWVROXFXejc2b2Q5
        VjhsL3lLRlZkOUY5cnYxWlBmaG4xaXNvYVJTSWVueXc3RW9ZL1d2aElqOS8rcGtP
        Skh1Q1ZSbDZJUDZiK01tZStDbTE2TzRoelFPTnZzU2pkclFCYm94TkloTTdUY25H
        dWVtcXlpUjVLY09ma2kxSW1iKzl1eWJvSGZWeDVpRndwU3BYQWFxQU9ZZ1B6TmVn
        TFJNSHpER3VFMm0zcGg2Y3hFY04xOW0zT0JRcm9nRVVobkFzZTJCSEJ4U1ZraDFR
        d29NLzJSY0NadjRYbnByK3hmamM5NmJITGs0eXRDdzJwQmlVWjBPMW9zZmFzSURh
        VWxKeUl0aUk3NWRaaVEzWVJrMnFnM0dweUhuaXlPVzFmd1pqbWNLb3cySDhKMDg2
        UE52SGZHN2ZESXNFdUV3RDdWQVhjb3ZmY2FLbHVwMURVQ1NWUjZ2UE9sbHZpNnRi
        RDVmZms4L0JHbm5wVDVtbGNDKzEydFQ5ZGlVdjVmQm1lcG5YeTU2T2xCSnE1RW1y
        RWRpZjBNakZaeUowOFVwTlFXNGI3SVlyWGNnK0NKK0lSVGpzajNLMXNTUHZKcG5s
        TXduWlpGTDVRZEYrQnZCenFWZ05TTU1mSnBvUExMeGhiYlFucitScWcrenZITmFv
        OTUxY1lUU2pWemFUcDFqU0M1bVNyZVNPTmExRHZsS3B5RHJ6dVc3RFZYWitNTUt3
        TWFLMzBUSytscURxQmVsQUZPdHc3OGU4RjF0QjRTSWxLZ0tLNE9EemRHMkpKRzJI
        S1ZkRTJGSW5CMC9wYTVYMTBicU9wc3JvRFNMU0NWSUVCSUNaZDRDY3NjYnZ6cDZ6
        RUFpYXk3WmhYUnlGNGJ2YmhtMG45anR6T3VLK25ua0dSNFgreEo4ZHRBRjczcDhQ
        aVBGRk5vUDJva3hsVnpyWDNnYWhyTTc4OUtTdmRxUUFMZ0tIdnVCRnVYVmdLRHdn
        OXJPdFl5WTU4N0RDWU9qb0R0djZUcmpPVFlHd3g5NUhFSXRVR0pLNXpWT0o5NUNB
        ZldaUjduRmZ6UTVreXNrZnBpVlJRRENwbGFXT1FTZkpnenZKYjFwdFVFNWE5bmps
        MmtzMnEwMlE1ZHVtZFgxb1MyWVVjbDFXdFljRFdvNGM3Z1NrUEZ3WC9WTjNFcU5Z
        ODJBUEx4K0UzR1BtL2Mxd1lQL0l4WmlkaGlSWWcwSjJya0NwcldReE1JOW42SlR5
        Z0YzMjlydzR2b0RnTTMwVU5mNGxjSFJFT0lWWTEyaFZyaTdLZUZSS05UempSZwp1
        MDBzN0o4OXA3MjQ4WG52ZFJLVmFZMHg4SkJiK0RZYkg4d3phb2dLYm84Ci0tLSB3
        a3FZZTllRnFVNld1UW9IYTkvL3FySmZBUk5GUjR5dGwyVlZncE9LVHVBCsM7HrQl
        ZUcUlkGMAlnJzxyb2kH2YzquWrNRRm7GHYARMM2AhmAPgLx6iZjbpQI2rikEu9xo
        GDeO4Ib1OEm5jbY=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1a523qrltc5tc2c97s7eku9stpt386g86jqd50zt2zdlpv7nn76yyfg69ra80ct06746j03chk3e83snj3gn0ctkgxwp96vat87j2z4js5yamnnf96eqgn6zlfqngg95jz24f58hysvud6qrdqtc3uqh6scmpdg4ergtu3pd8zkpnsczfs6sq80nu5ch5g6uf6l95532qec80c86pw95tqsnmvcmmlph8xwvzwuea0x3r90qq05jesjkg0nt98qr42dpfaxzr67zmuchctncy095ccvv3ruc93fnrzn4fsxjtc67ryvzr27tu7vfcnwts3ul6jal5s99gas2eewzcmglq3tz2xre62z53mcpksranxt9qj46xsy9zlzn5lkrucj9rtdmnpa9aess9k58l84v7vgrnvmuew220zmlhdpr04uzpssdxj2hr5nk2vxx8u3mj6cdzhkju4s79rm3jsznpczhyae3qxqg3xwlyysq5v58668qwtargda66fjrexttzx7vhvzjvdv393zuq9cegqwduhfj7w4c2eksrcrrfqzay5e53drumuh8s0s2ygu9fez2qexl3gpxz5xufcef24z5epcs4z6vuzkfls6ur2zzfw9qmhjr4sph7f964gjy895fr6gjgmhlzef86xkc677273wah2xjut28twrtmgwktrwp080q6yl59zxnjyspssjy4ag6yxkgnnhd4u26ysrsevchvaph43yyr8q4ecqr8fttl2v6szjqjl3r7nzjq4j320qgadr5yg39stfq5yqrc7v5h2trw5rwe38xnyccx7fphtqc6tcqmqjzsjyxxfksascahczg3qs3rrwfk8snd4j20amdyufthz8pe8j29zual8pyqa99fjfh88z02jtua53k6t9e7cf59tshfh3ya3nnr22q55qvnqhq2jjnvg7j6y2tfz5f035kypuyx7xdzhaqrndztr3plu43dw0dqljsjtww940ahvp3enkpfzjnvunrntfh5cv0nwxm5sgpcesp6c5kn5zyled8f5shmh9502u5q76lxv394yckdhg8tkxy0e6wqgj8zzc4kn3czvk5wq2f65au3h8wh0e5ywxuff95tp6e3s7wrwdv2rmpud0scgjzpg2rr7uqyzchygu6kx7ukm9d967e0r6sru9urd83rqc4cfxweryutd752ef73te73tnn4axtejvjk3qa8rjqhpvkld8kqpg8yshxrd0cfwqjq8kee2tqm23hfueuu2eqnre6yrm472wx8eykgffghzl3g0y0fd6xjqw224p2zuea77q46cfe5vxwwsvnc5vr35vkvk6q96vjfdnpdtpfnnvmst6djjxmxgdgr9pfjyl8s4qsl6k4ldm6y60xq0g38jnerajlplzp4pwspw4hq4wg29tl2ccxzcv9xwhspytzzng3rhp8qscysyxww8vrm46x9q4fk3jvjv5zjtgaadfnqlw5uqlqh3d66dzlfp2yp33j23w8h9mn6cenx8v36ndyyvk6yjz663rcj4jn2ykryupj48j54r9se2dumw8v0gun5wunj8ft2qxkm2euaj08mzhp6g9fs33dqjc9hyzvsk4a4czxk74urmht906xe99yxjgukvd6v3vgeg3c4f8cttp745cgf5cgkxy94v8ug8awt38yhntvjg28dvmrmv9xfr4s5v8yakt2df3hw7afa6ewqe4upyd5vjpy6sz2pg9fafuwp2xw6y75q9dvwn9n9r232n39ty8hjq7sjw95tmyyarkuwdla85p5gndvu2he5s7eu52cxhm7tfd5nsrnz5tex2pnkggl93grfcsaa0h9tkpknew52n3ew7rxhp06tlpytcvqcrf7yaaeqsl8r09qm9c5ernmx52rt0mx9j66luasmz9y6dmqduwj9kq7q85exdf7q
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-21T02:06:08Z"
  mac: ENC[AES256_GCM,data:j4AvbXyH+a0xLW+NdlieasLl8KytlzX/nfGXycOh2kcBMzHPd41x6s2HtIZbgn+VlWwJXTqTOL3LIzj+DNdS9S0mfyusJ1jM4QOsWNnuKrekaWbQRAqMaD1qxFqgpCIoYfIE2RdWbwqhuuqLF4XXzjkRoIc8IibMw/79LAZAKnQ=,iv:HiywYZ2T3Nm134zjYO5iLLNdjZL5t6iaQyIuxjaDPZI=,tag:5VJzhcfQg0JE3seiK0C+Ug==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
