apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-tunnel-secret
spec:
  refreshInterval: 10s
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: cloudflare-tunnel-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: TUNNEL_TOKEN
      remoteRef:
        key: secrets/network/cloudflare-tunnel
        property: TUNNEL_TOKEN
