---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/system-upgrade/tuppr/ks.yaml

patches:
  - target:
      kind: Kustomization
      name: rook-ceph
    patch: |-
      - op: replace
        path: /spec/path
        value: ./kubernetes/infrastructure/production/system-upgrade/tuppr/app
  - target:
      kind: Kustomization
      name: rook-ceph-cluster
    patch: |-
      - op: replace
        path: /spec/path
        value: ./kubernetes/infrastructure/production/system-upgrade/tuppr/upgrade
