---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/flux-system/flux-instance/ks.yaml

patches:
  - target:
      kind: Kustomization
      name: flux-instance
    patch: |-
      - op: replace
        path: /spec/path
        value: ./kubernetes/infrastructure/production/flux-system/flux-instance/app
