apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: garage-ui-secrets
spec:
  refreshInterval: 10s
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: garage-ui-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: GARAGE_UI_AUTH_OIDC_CLIENT_ID
      remoteRef:
        key: secrets/storage/garage-ui/secrets
        property: GARAGE_UI_AUTH_OIDC_CLIENT_ID
    - secretKey: GARAGE_UI_AUTH_OIDC_CLIENT_SECRET
      remoteRef:
        key: secrets/storage/garage-ui/secrets
        property: GARAGE_UI_AUTH_OIDC_CLIENT_SECRET
    - secretKey: GARAGE_UI_GARAGE_ADMIN_TOKEN
      remoteRef:
        key: secrets/storage/garage-ui/secrets
        property: GARAGE_UI_GARAGE_ADMIN_TOKEN
