---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/observability/gatus/app

patches:
  - target:
      kind: HelmRelease
      name: gatus-sidecar
    path: ./helmrelease.yaml
