---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/observability/grafana-operator/ks.yaml

patches:
  - target:
      kind: Kustomization
      name: grafana-operator
    patch: |-
      - op: replace
        path: /spec/path
        value: ./kubernetes/infrastructure/production/observability/grafana-operator/app
  - target:
      kind: Kustomization
      name: grafana-instance
    patch: |-
      - op: replace
        path: /spec/path
        value: ./kubernetes/infrastructure/production/observability/grafana-operator/instance
