apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-secrets
spec:
  refreshInterval: 10s
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: authentik-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: BOOTSTRAP_EMAIL
      remoteRef:
        key: secrets/security/authentik/secrets
        property: BOOTSTRAP_EMAIL
    - secretKey: BOOTSTRAP_PASSWORD
      remoteRef:
        key: secrets/security/authentik/secrets
        property: BOOTSTRAP_PASSWORD
    - secretKey: BOOTSTRAP_TOKEN
      remoteRef:
        key: secrets/security/authentik/secrets
        property: BOOTSTRAP_TOKEN
    - secretKey: SECRET_KEY
      remoteRef:
        key: secrets/security/authentik/secrets
        property: SECRET_KEY
