apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: securitypolicy-prometheus-secrets
spec:
  refreshInterval: 10s
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: securitypolicy-prometheus-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: client-secret
      remoteRef:
        key: secrets/observability/kube-prometheus-stack/securitypolicy
        property: client-secret
