---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/database/dragonfly/ks.yaml

patches:
  - target:
      kind: Kustomization
      name: dragonfly
    patch: |-
      - op: replace
        path: /spec/path
        value: ./kubernetes/infrastructure/production/database/dragonfly/app
