---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/external-services/dockhand/external

patches:
  - target:
      kind: HTTPRoute
      name: dockhand
    path: ./httproute.yaml
