apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openbao-test
  namespace: external-secrets
spec:
  refreshInterval: 10s
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: openbao-test
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: username
      remoteRef:
        key: secrets/test/demo
        property: username
    - secretKey: password
      remoteRef:
        key: secrets/test/demo
        property: password
