apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openbao-transit-token
spec:
  refreshInterval: 10s
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: openbao-transit-token
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: token
      remoteRef:
        key: secrets/external-secrets/openbao/transit-token
        property: token
