---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openbao
spec:
  values:
    server:
      ha:
        raft:
          config: |
            ui = true

            listener "tcp" {
              tls_disable = 1
              address = "[::]:8200"
              cluster_address = "[::]:8201"
            }

            storage "raft" {
              path = "/openbao/data"
            }

            service_registration "kubernetes" {}

            seal "transit" {
              address = "https://openbao.internal.sud0.net"
              key_name = "openbao-unseal"
              mount_path = "transit/"
              tls_skip_verify = "false"
            }
      gateway:
        httpRoute:
          hosts:
            - openbao.sud0.net
