---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/external-secrets/openbao/app
  - ./externalsecret.yaml

patches:
  - target:
      name: openbao
      kind: HelmRelease
    path: ./helmrelease.yaml
