apiVersion: source.extensions.fluxcd.io/v1beta1
kind: ArtifactGenerator
metadata:
  name: monorepo
  namespace: flux-system
spec:
  sources:
    - alias: monorepo
      kind: GitRepository
      name: flux-system
  artifacts:
    - name: infrastructure
      originRevision: "@monorepo"
      copy:
        - from: "@monorepo/kubernetes/infrastructure/production/**"
          to: "@artifact/production/"
        - from: "@monorepo/kubernetes/infrastructure/base/**"
          to: "@artifact/base/"
        # - from: "@monorepo/kubernetes/components/**"
        #   to: "@artifact/components/"
    - name: apps
      originRevision: "@monorepo"
      copy:
        - from: "@monorepo/kubernetes/apps/base/**"
          to: "@artifact/base/"
        - from: "@monorepo/kubernetes/apps/production/**"
          to: "@artifact/production/"
        # - from: "@monorepo/components/**"
        #   to: "@artifact/components/"
