---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/security/trivy/ks.yaml

patches:
  - target:
      kind: Kustomization
      name: trivy
    patch: |-
      - op: replace
        path: /spec/path
        value: ./kubernetes/apps/production/security/trivy/app
