---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/observability/kube-prometheus-stack/ks.yaml

patches:
  - target:
      kind: Kustomization
      name: kube-prometheus-stack
    patch: |-
      - op: replace
        path: /spec/path
        value: ./kubernetes/infrastructure/production/observability/kube-prometheus-stack/app
