---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/rancher/local-path-provisioner/ks.yaml

patches:
  - target:
      kind: Kustomization
      name: local-path-provisioner
    patch: |-
      - op: replace
        path: /spec/path
        value: ./kubernetes/infrastructure/production/rancher/local-path-provisioner/app
