apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: adguard-sync-secret
spec:
  refreshInterval: 10s
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: adguard-sync-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: ORIGIN_PASSWORD
      remoteRef:
        key: secrets/network/adguard/sync
        property: ORIGIN_PASSWORD
    - secretKey: ORIGIN_USERNAME
      remoteRef:
        key: secrets/network/adguard/sync
        property: ORIGIN_USERNAME
    - secretKey: REPLICA1_PASSWORD
      remoteRef:
        key: secrets/network/adguard/sync
        property: REPLICA1_PASSWORD
    - secretKey: REPLICA1_USERNAME
      remoteRef:
        key: secrets/network/adguard/sync
        property: REPLICA1_USERNAME
