---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/productivity/kanbn/ks.yaml

patches:
  - target:
      kind: Kustomization
      name: kanbn
    patch: |-
      - op: replace
        path: /spec/path
        value: ./kubernetes/apps/production/productivity/kanbn/app
  - target:
      kind: Kustomization
      name: kanbn-database
    patch: |-
      - op: replace
        path: /spec/path
        value: ./kubernetes/apps/production/productivity/kanbn/database
