---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/productivity/renovate-operator/ks.yaml

patches:
  - target:
      kind: Kustomization
      name: renovate-operator
    patch: |-
      - op: replace
        path: /spec/path
        value: ./kubernetes/apps/production/productivity/renovate-operator/app
