apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cert-manager-secret
spec:
  refreshInterval: 10s
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: cert-manager-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: api-token
      remoteRef:
        key: secrets/network/cloudflare-dns/token
        property: api-token
