apiVersion: v1
kind: ConfigMap
metadata:
  name: kanbn-env
data:
  NEXT_PUBLIC_BASE_URL: https://kanbn.sud0.net
  S3_REGION: us-east-1
  S3_ENDPOINT: https://s3.sud0.net
  S3_FORCE_PATH_STYLE: "true"
  S3_AVATAR_UPLOAD_LIMIT: "10485760"
  NEXT_PUBLIC_STORAGE_URL: https://s3.sud0.net
  NEXT_PUBLIC_AVATAR_BUCKET_NAME: kan
  NEXT_PUBLIC_ATTACHMENTS_BUCKET_NAME: kan
  NEXT_PUBLIC_STORAGE_DOMAIN: s3.sud0.net
  NEXT_PUBLIC_ALLOW_CREDENTIALS: "false"
  NEXT_PUBLIC_DISABLE_SIGN_UP: "false"
  LOG_LEVEL: info
  OIDC_DISCOVERY_URL: https://authentik.sud0.net/application/o/kanbn/.well-known/openid-configuration
