apiVersion: v1
kind: Secret
metadata:
  name: kanbn-secrets
stringData:
  S3_ACCESS_KEY_ID: GKb0ee732ba16b7de89ea0cc31
  S3_SECRET_ACCESS_KEY: 2793b7f94c1300ac5e858caca34155aea72b47a98f3fb3fc0dd35f72681764fb
  BETTER_AUTH_SECRET: WmYOjny38dEfQg1h5Nndblt2gUYPcc35
  OIDC_CLIENT_ID: 2FQPX2eylduK1qNelXm49QOjJSac4MQOe4NXPzco
  OIDC_CLIENT_SECRET: zFNXTIreNdzUTeYyW8OMC8NtKsGsVECSAplgj2qaDMUHwLpGZTIeypMNFOK6FlFp2VSQSUsyX6HNC26MpdzbyHEuFBSgcHZ2ZTv2ND0Gz460NQSzSsyAmnAQgwv8a2rb
