---
connectivity:
  checker:
    target: 1.1.1.1:53
    interval: 1m

endpoints:
  - name: Cloudflare
    group: connectivity
    url: icmp://1.1.1.1
    interval: 1m
    conditions:
      - "[CONNECTED] == true"

  - name: Google
    group: connectivity
    url: icmp://8.8.8.8
    interval: 1m
    conditions:
      - "[CONNECTED] == true"

  - name: Quad9
    group: connectivity
    url: icmp://9.9.9.9
    interval: 1m
    conditions:
      - "[CONNECTED] == true"

metrics: true

storage:
  type: sqlite
  caching: true
  path: ${GATUS_CONFIG_PATH}/gatus.db

ui:
  title: Statusd0 | Gatus
  description: Service Monitor
  dashboard-heading: Sud0 Services
  dashboard-subheading: If a service is red it may either be down for maintenance or actually broken. If the service is not restored in an hour then please reach out to me.
  header: Status
  logo: https://gitlab.com/uploads/-/system/user/avatar/40901175/avatar.png?v=1788824686
  link: https://gitlab.com/nadd3r
  buttons:
    - name: Gitlab
      link: https://gitlab.com/nadd3r
    - name: Homelab
      link: https://gitlab.com/nadd3r/home-ops

announcements:
  - timestamp: 2026-09-07T19:55:00Z
    type: warning
    message: These services are currently being developed, as such they are likely to break or change over time.
  - timestamp: 2026-09-07T19:55:00Z
    type: information
    message: Maintenance is planned for every Monday from 7PM to 10PM EST. This may not affect the services you use. If a service you use is affected keep an eye on this page for when it is available again.

web:
  port: ${GATUS_WEB_PORT}
