---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/network/adguard-dns/app

patches:
  - target:
      kind: HelmRelease
      name: adguard
    path: ./helmrelease.yaml
