---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/external-services/openbao-internal/ks.yaml

patches:
  - target:
      kind: Kustomization
      name: openbao-internal
    patch: |-
      - op: replace
        path: /spec/path
        value: ./kubernetes/apps/production/external-services/openbao-internal/external
