apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sillytavern-secrets
spec:
  refreshInterval: 10s
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: sillytavern-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: client-secret
      remoteRef:
        key: secrets/ai/sillytavern/secrets
        property: client-secret
    - secretKey: admin-password
      remoteRef:
        key: secrets/ai/sillytavern/secrets
        property: admin-password
