---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/ai/sillytavern/app
  - ./externalsecret.yaml

patches:
  - target:
      kind: HelmRelease
      name: sillytavern
    path: ./helmrelease.yaml
