apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rook-ceph-dashboard-password
spec:
  refreshInterval: 10s
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: rook-ceph-dashboard-password
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: password
      remoteRef:
        key: secrets/rook-ceph/dashboard/password
        property: password
