---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/external-services/truenas/ks.yaml

patches:
  - target:
      kind: Kustomization
      name: truenas
    patch: |-
      - op: replace
        path: /spec/path
        value: ./kubernetes/apps/production/external-services/truenas/app
