---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vaultwarden
spec:
  values:
    server:
      route:
        main:
          hostnames:
            - "vaultwarden.sud0.net"
