---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/security/vaultwarden/app
  - configmap.yaml
  - externalsecret.yaml

patches:
  - target:
      kind: HelmRelease
      name: vaultwarden
    path: ./helmrelease.yaml
