---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/cert-manager/cert-manager/ks.yaml

patches:
  - target:
      kind: Kustomization
      name: cert-manager
    patch: |-
      - op: replace
        path: /spec/path
        value: ./kubernetes/infrastructure/production/cert-manager/cert-manager/app
