---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/ai/open-webui/ks.yaml

patches:
  - target:
      kind: Kustomization
      name: open-webui
    patch: |-
      - op: replace
        path: /spec/path
        value: ./kubernetes/apps/production/ai/open-webui/app
