---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/network/k8s-gateway/ks.yaml

patches:
  - target:
      kind: Kustomization
      name: k8s-gateway
    patch: |-
      - op: replace
        path: /spec/path
        value: ./kubernetes/infrastructure/production/network/k8s-gateway/app
